image: archlinux
packages:
  - meson
  - wayland
  - wayland-protocols
  - cairo
  - pango
  - gdk-pixbuf2
  - gtk3
  - systemd
sources:
  - https://github.com/emersion/mako
tasks:
  - setup: |
      cd mako
      meson build
  - build: |
      cd mako
      ninja -C build
