#!/bin/sh -eu

usage() {
	echo "Usage: makoctl <command> [options...]"
	echo ""
	echo "Commands:"
	echo "  dismiss [-a|--all]    Dismiss the last or all notifications"
	echo "  invoke [action] [id]  Invoke an action on the notification"
	echo "                        with the given id, or the last"
	echo "                        notification if none is given"
	echo "  list                  List notifications"
	echo "  reload                Reload the configuration file"
	echo "  help                  Show this help"
}

call() {
	busctl -j --user call org.freedesktop.Notifications /fr/emersion/Mako \
		fr.emersion.Mako "$@"
}

if [ $# -eq 0 ] || [ $# -gt 3 ]; then
   usage
   exit 1
fi

case "$1" in
"dismiss")
	[ $# -lt 2 ] && action="" || action="$2"
	case "$action" in
	"-a"|"--all")
		call DismissAllNotifications
		;;
	"")
		call DismissLastNotification
		;;
	*)
		echo "makoctl: unrecognized option '$2'"
		exit 1
		;;
	esac
	;;
"invoke")
	[ $# -lt 2 ] && action="default" || action="$2"
	[ $# -lt 3 ] && id="0" || id="$3"
	call InvokeAction "us" "$id" "$action"
	;;
"list")
	call ListNotifications
	;;
"reload")
	call Reload
	;;
"help"|"--help"|"-h")
	usage
	;;
*)
	echo "makoctl: unrecognized command '$1'"
	exit 1
	;;
esac
